[package]
name = "kairos_asset"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Async asset server and handle system for the Kairos engine, extracted as a standalone crate"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(docsrs)", "cfg(docsrs_dep)"] }

[dependencies]
async-fs = "2.1"
atomicow = { version = "1.1", default-features = false, features = ["std"] }
crossbeam-channel = "0.5.15"
futures-io = "0.3"
futures-lite = "2.6.1"
kairos_collections = { path = "../kairos_collections" }
kairos_ecs = { path = "../kairos_ecs" }
kairos_tasks = { path = "../kairos_tasks" }
ron = "0.12"
serde = { version = "1.0.228", features = ["derive"] }
uuid = { version = "1", features = ["v4", "serde"] }
