shader_selector_height = 20.0
shader_selector_menu_border = 10.0
shader_selector_menu_min_width = 10.0
shader_selector_submenu_width_factor = 0.7

texture_label_height = 60.0
texture_background_color = "#32323280"
texture_drag_hover_background_color = "#0050c84d"
texture_empty_stroke_color = "#464646"
texture_fill_stroke_color = "#5a5a5a"
texture_drag_hover_stroke_color = "#4696ff"
texture_corner_radius = 4
texture_stroke_width = 1.0
