row_height = 20.0
preview_default_size = 512
camera_fov = 60.0
camera_direction = [0.0, -0.6, 1.0, 0.0]
camera_orbit_speed = 0.008
camera_zoom_speed = 0.01
camera_min_distance = 0.03
camera_max_distance = 3000.0
