pub const SHADER_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 64;
pub const SHADER_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 16;

pub const MATERIAL_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 128;
pub const MATERIAL_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 16;

pub const TOML_TABLE_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 32;
pub const TOML_TABLE_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 8;

pub const TEXT_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 128;
pub const TEXT_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 16;

pub const FONT_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 4;
pub const FONT_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 2;

pub const SERIALIZED_MATERIAL_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 32;
pub const SERIALIZED_MATERIAL_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 8;

pub const SYNTAX_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 4;
pub const SYNTAX_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 2;
