cargo-features = ["profile-rustflags"]

[profile.release]
rustflags = ["-C", "target-cpu=native"]

[profile.bench]
rustflags = ["-C", "target-cpu=native"]

[package]
name = "kairos_engine"
version = "0.1.0"
edition = "2024"
description = "A Game Engine"
license = "MIT OR Apache-2.0"

[dev-dependencies]
criterion = "0.8.2"

[dependencies]
toml = "1.1.2"
anyhow = "1.0"
crossbeam-channel = "0.5.15"
bytemuck = { version = "1.25.0", features = ["derive"] }
tokio = { version = "1.52.3", features = ["full"] }
rayon = "1.12.0"
# petgraph = "0.8.3"
winit = { version = "0.30", features = ["android-native-activity"] }
env_logger = "0.10"
log = "0.4"
native-dialog = "0.9.6"
serde = "1.0.228"
sonic-rs = "0.5.7"
duplicate = "2.0"
paste = "1.0"
image = { version = "0.25.10", features = ["png"] }
wgpu = "29.0.3"
pollster = "0.3"
# eframe = { version = "0.34.2", features = ["wgpu"] }
egui = "0.34.2"
egui_extras = { version = "0.34.2", features = ["all_loaders"] }
emath = "0.34.2"
epaint = "0.34.2"
# egui_dock = "0.18.0"
egui-winit = "0.34.2"
egui-wgpu = "0.34.2"
parking_lot = "0.12.5"
# rapier3d = { version = "0.32.0", features = [ "simd-nightly", "parallel", "serde-serialize" ] }
# kira = "0.12.0"
# puffin = "0.20.0"

[[bench]]
name = "vec_benchmark"
harness = false
