cargo-features = ["profile-rustflags"]

[workspace]
members = ["kairos_engine", "kairos_ecs_macros"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[profile.release]
rustflags = ["-C", "target-cpu=native"]

[profile.bench]
rustflags = ["-C", "target-cpu=native"]
