pub const TEXTURE_ASSETS_CAPACITY: usize = 512;
pub const TEXTURE_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 128;
pub const TEXTURE_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 16;

pub const MESH_ASSETS_CAPACITY: usize = 512;
pub const MESH_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 128;
pub const MESH_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 16;

pub const SHADER_ASSETS_CAPACITY: usize = 128;
pub const SHADER_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 64;
pub const SHADER_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 16;

pub const MATERIAL_ASSETS_CAPACITY: usize = 512;
pub const MATERIAL_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 128;
pub const MATERIAL_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 16;
