pub const TEXTURE_ASSETS_CAPACITY: usize = 512;
pub const TEXTURE_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 128;
pub const TEXTURE_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 16;

pub const MESH_ASSETS_CAPACITY: usize = 512;
pub const MESH_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 128;
pub const MESH_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 16;

pub const SHADER_ASSETS_CAPACITY: usize = 128;
pub const SHADER_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 64;
pub const SHADER_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 16;

pub const MATERIAL_ASSETS_CAPACITY: usize = 512;
pub const MATERIAL_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 128;
pub const MATERIAL_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 16;

pub const AUDIO_ASSETS_CAPACITY: usize = 512;
pub const AUDIO_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 128;
pub const AUDIO_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 16;

pub const TOML_TABLE_ASSETS_CAPACITY: usize = 64;
pub const TOML_TABLE_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 32;
pub const TOML_TABLE_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 8;

pub const FONT_ASSETS_CAPACITY: usize = 8;
pub const FONT_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 4;
pub const FONT_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 2;

pub const SYNTAX_ASSETS_CAPACITY: usize = 8;
pub const SYNTAX_ASSETS_LOADED_CHANNEL_BUFFER_SIZE: usize = 4;
pub const SYNTAX_ASSETS_DROP_CHANNEL_BUFFER_SIZE: usize = 2;
