[package]
name = "kairos_macro_utils"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "A collection of utils for Kairos Engine"

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
toml_edit = { version = "0.25.1", default-features = false, features = [
  "parse",
] }

[package.metadata.docs.rs]
rustdoc-args = [
  "-Zunstable-options",
  "--generate-link-to-definition",
  "--generate-macro-expansion",
]
all-features = true
