pub const MAX_SPATIAL_TRACK_COUNT: u8 = 32;
pub const MAX_SPATIAL_LISTENER_COUNT: u8 = 2;
pub const SPATIAL_AUDIO_CUT_OFF_DISTANCE_SQ: f32 = 512.0 * 512.0;
pub const SPATIAL_AUDIO_TRACK_LEAVING_DURATION: f32 = 0.3;
pub const SPATIAL_REVERB_DEFAULT_DISTANCE_RANGE: f32 = 100.0;
pub const SPATIAL_REVERB_DEFAULT_MIN_VOLUME: f32 = -12.0;
pub const SPATIAL_REVERB_DEFAULT_MAX_VOLUME: f32 = 24.0;
