title = "Project"

[hierachy]
directory_header_color = "#dcdcb4"
file_header_color = "#c8c8c8"
selected_file_background_color = "#3c4b64"
file_suffix_color = "#787878"
file_header_size = 11.0
file_icon_size = 18.0
selected_file_background_corner_radius = 4

[content]
label_color = "#c8c8c8"
selected_background_color = "#3c4b64"
selected_background_corner_radius = 4
icon_size = 60.0
label_font_size = 10.0
label_height = 28.0
cell_spacing_x = 24.0
cell_spacing_y = 12.0
