title = "Scene"
cam_default_position = [0.0, 1.0, -2.0, 0.0]
cam_default_target = [0.0, 0.0, 0.0, 0.0]
cam_default_fov = 45.0
cam_default_near = 0.3
cam_default_far = 100.0
cam_default_orbit_speed = 0.005
cam_default_zoom_speed = 0.1
cam_default_min_distance = 0.3
cam_default_max_distance = 100.0
